---
output: pdf_document
---

\backmatter
\onehalfspacing

# Corrections {.unnumbered} 
  \setcounter{chapter}{5}
	\setcounter{section}{0}

We describe the corrections we made to the original file in detail below. 
We corrected about 76 typographical errors throughout the file. Major changes among these include several errroneous mathematical derivations. For example, in Chapter 2, there was a parenthesis error in deriving the limit of the factor $(1 - p)^{N_{V} - 1 - k}$ factor of probability $p_{k}$ for the Erdős-Rényi model. The probability $p_{k}$ of the Wattts-Strogatz model was also incorrect, as there was an error in the denominator; it was supposed to be $(k - r)!$ rather than just $k - r$. In the explanation of how the Erdős-Rényi model is derived from ERGMs, there was an error in the equation that followed--the expression $exp \left(L(g)log \left(\frac {p} {1-p} \right) - \frac {N_{V}(N_{V} - 1)} {2} log \left( \frac {p} {1-p} \right) \right)$ should have been $exp \left(L(g)log \left(\frac {p} {1-p} \right) - \frac {N_{V}(N_{V} - 1)} {2} log \left( \frac {1} {1 - p} \right) \right)$. 
Minor changes include turning ordinary letters into in-line mathematical symbols (e.g. "a graph G" versus "a graph $G$"), incorrect word choice (e.g. "edges" instead of "vertices"), incorrect figure reference (e.g. Figure 3.2 instead of Figure 2.2, as intended), spacing issues, captialization ("Statistics" instead of "statistics"), and other miscellaneous grammatical errors. We also included instances where were added braces ({}) to subscripts of variables in equations--even though they are not visible to the reader when rendered--in this count. For example, when typsetting equations, the variable $N_{V}$ should not be typesetted as $N\_V$ but instead, more correctly as $N\_\{V\}$ even though both will output the same variable $N_{V}$ when rendered. 
There were also four footnote errors. In the original version, the footnotes in the Introduction, Chapter 1, and Chapter 2 did not display the correct text. There were also seven incorrect table references in the chapters and the appendix. We have corrected both of these issues as well. 

There were about five instances of removing entire sentences for the sake of conciseness. This includes things such as the power law distribution as well as the definition of order, size, trail, and clique, which we did not end up using. The normalizing constant needed in deriving the Erdős-Rényi model from ERGMs was never fully proven in the chapter, and is now left as a footnote with sources that lead to a more-detailed derivation. 

There were about 61 instances where we removed, revised, added, and/or rearranged words, sentences and/or paragraphs for the sake of clarity. 
We extended our discussion of certain definitions that would allow the reader to understand how these definitions apply to real-world social networks and why they are important. This includes adding a Facebook and Twitter example to explain directed and undirected networks, and also broader explanations for all four types of centrality. 
We added a description regarding scaling when it comes to comparing centrality measures in the lawyer and karate examples and in the simulation study. Because the networks we are comparing having approximately the same number of vertices, it is possible for us to compare their centrality measures without having to scale them. 
We included a deeper description of the contents recorded in each table that was originally in the beginning of Chapter 3, now moved to the middle Chapter 3 (after the description of the algorthms for the models. The values in the cells of the table are either the true value of the network statistic associated with the Facebook network or an estimate for each model along with a standard deviation. This was further emphasized by the addition of "(estimate $pm$ standard deviation)" in the description of each table. 
We added a table of average network statistics for the lawyer and karate networks to summarize our results. The tables in Chapter 3 have also been updated with abbreviations to the names of network statistics and a reduced number of digits in the estimated values so that we are only working with three or four significant figures. 
We also addressed the problem of low stochasticity (i.e. small values of standard deviation, small errors) in the Conclusion. 
We made two edits to the headers of code chunks so that the code chunks do not actually run when the file itself is being knit. We do not need them to run because the images that they generate have already been inserted into the body of the text through other means. There was also at least one case where we added more comments to the code chunks. 

There was an issue citing certain sources, namely, Kolaczyk's books, that were referenced in the text manually with in-text citations but ended up not appearing in the References section; we added these citations to References manually. We also added seven other sources to the Reference section that may prove useful in further research (e.g. Becky Danning '16's undergraduate thesis and Bryan and Leise's paper on the Google Page Rank). We also added four additional in-text citations throughout the thesis. 


