---
author: 'Levi Lee'
date: 'April 05, 2017'
division: 'Statistics'
advisor: 'Amy Wagaman'
department: 'Mathematics and Statistics'
title: 'A Simulation Study Using Random Graph Models to Fit Social Networks'
abstract: >
  `r paste(readLines('abstract.Rmd'), collapse = '\n')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is # needed on the line after the >.
acknowledgements: >
  This thesis would not have been possible without the support of so many people. 
  First and foremost, I would like to thank everyone currently from the Mathematics and Statistics departments along with some previous faculty as well. In particular, Professor Xiaofei (Susan) Wang and Professor Eunice Kim were some of the first people that really got me heavily involved with R and R-Studio through the coursework they provided. I would never imagine that one day, I would be doing something so advanced with such software.
  I would also like to thank my fellow Statistics majors for always providing such amazing help when I get stuck. My gratitude goes to Stephany Flores-Ramos '17, Melody Owen '17, Jordan Browning '17, and Muling Si '17 for being such wonderful peers in Advanced Data Analysis and for always bearing with me. Seeing how wonderfully they all code really inspired me to improve my own skills as well. Special thanks also goes to Ningyue (Christina) Wang '16 for all the senior advice when I was a junior.
  To all the students, faculty, and staff who knew I was working on this project, thank you for the constant moral support. Those who also had a hand in helping with this project, even if it was just moral support, are truly a cut above. I am especially grateful to Roy Andrews '80 from the Writing Center, Caleb Ki '17, and Azka Javaid '17, also Statistics majors, who were kind enough to read over my thesis and provide valuable feedback. Special thanks to Nguyen (Johnson) Tran, a childhood friend from back home in Florida, who was kind enough to gift me a wonderful textbook on Statistics, which proved to be very useful in my research. 
  I want to dedicate this next paragraph to my family. Without their love and support, I would not be at Amherst today. Since the day I started school, my parents have done everything in their power to make sure the only thing I ever really need to focus on was my education. Nothing could ever amount to the sacrifices they have made, and I now realize that being able to focus solely on academics was a privilege that not everyone had. 
  My penultimate thanks goes to Professor Nicholas Horton, whom I have had the pleasure of having a professor for two courses in a row. He is a professor, a mentor, and a coach who really has a sense of the direction Statistics is taking, and is really preparing us all to "think with data."
  Finally, I want to give my thanks to Professor Amy Wagaman, who has been my "three-times advisor" for Mathematics, Statistics, and my Mathematics Thesis. She has been an amazing advior in all regards, and I cannot thank her enough for her patience, understanding, and dedication to my learning. Working on such a project has really been challenging, but was definitely the highlight of my final year in college. It is thanks to her that I was able to explore the facinating world of networks and pursue graduate study in this field. I hope that this project has made her proud. 
  
bibliography: bib/thesis.bib
# Modify your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
output: 
  acstats::amherst_thesis:
    toc: true
lot: true
lof: true
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 12 and 13 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting PDF file enclose it in a block like this.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the acstats package is
# installed and loaded. This acstats package includes
# the template files for the thesis and also two functions
# used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(acstats)){
  library(devtools)
  devtools::install_github("Amherst-Statistics/acstats")
}
library(acstats)
```

```{r setup, include=FALSE}
library(sand)
library(igraph)
library(network)
library(sna)
library(statnet)
library(ergm)
library(xtable)

options(xtable.comment = FALSE)
options(digits = 4)
```

\onehalfspacing

<!--
This is the way to split your thesis into chapters and then include each of the chapters seperately.  You can Knit the Rmd files corresponding to each chapter individually and then put them all back together by Knit-ing this document.

This is an R chunk and chap0.Rmd refers to the Introductory chapter.  Feel free to name this file as something else, but don't forget to change the argument to in `child = ` below!
-->

```{r intro, child = 'chap0.Rmd'}
```

<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

```{r chapter1, child = 'chap1.Rmd'}
```


<!--
Immediately below is the chunk for Chapter 2.
--> 

```{r chapter2, child = 'chap2.Rmd'}
```




```{r chapter3, child = 'chap3.Rmd'}
```



<!--
Add other chunks here for other chapters in your thesis.  Note that if you use the `child =` parameter, you can't include anything else in your chunk.
-->


```{r conclusion, child = 'conclusion.Rmd'}
```

\onehalfspacing

```{r corrections, child = 'corrections.Rmd'}
```

<!--
The bib chunk below must go last in this document according to how R Markdown renders.  More info is at http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
-->

\singlespacing

```{r bib, child = 'bibliography.Rmd'}
```



